/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b4c44d00-2e6b-45e4-b8b3-26020243fa4d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1c1fJC3zf",
    "aws_user_pools_web_client_id": "7n226d3tk1fqqccksgr03071vp",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xgwruo5plbffll3sv7rpwmzaga.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yxgv3bn64zdq5bc5cqyxck3w6u"
};


export default awsmobile;
